config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
  class TasksController < ApplicationController

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new



  end

  def create

    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)

  end

  def edit
    @task = Task.find(params[:id])
  end

    def update
      @task = Task.find(params[:id])
      @task.update(task_params)
      redirect_to task_path(@task)

    end

    def destroy
      @task = Task.find(params[:id])
      @task.destroy
      redirect_to tasks_path

    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>




<%= form_for @task do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>


  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', tasks_path('/tasks')%>

app/views/tasks/index.html.erb
  <strong>Title:</strong>
  <% @tasks.each do |task| %>

  <ul>
    <li>

      <input type="checkbox"   >








      <%= link_to task.title, task_path(task) %>
      <%= task.completed%>



    </li>
  </ul>









  <%end%>

  <%=
link_to 'New Task', tasks_new_path

%>





<%# Update the index.html.erb view with the link_to helper to build the links. %>

app/views/tasks/new.html.erb
<h1>New Task</h1>




<%= form_for @task do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>


  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', tasks_path('/tasks')%>

app/views/tasks/show.html.erb
<h1>
  <%= @task.title %>
</h1>

<h4>
  <%= @task.details%>
</h4>





<p>





  <%= @task.completed ? "This task is completed" : "This task is not completed yet" %>



</p>


<a href="/tasks">Go Back</a>




<%=
link_to 'Edit', edit_task_path(@task)


%>

<%= link_to "Delete",
task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>


<%#
4 - As a user, I can view the details of a task
We now have a list of tasks, and we would like to click on the task title and navigate to a new page, displaying the details of this task. Following the conventions from the lecture, add a new route, a new controller action and a new view. This action should find a specific task, thanks to its id, directly from params.

Update the index.html.erb view with the link_to helper to build the links.

⚠️ Again, in the view, do not focus on coding the checkboxes visual for now. You will have the opportunity to code it in the optional questions. %>